### ISSUE TITLE
Safe Delete Mode Disabled throws Error

### ISSUE THREAD

**Issue by justinjeffery-ipf** [nautobot/nautobot-plugin-ssot-ipfabric#115]
### Environment
* Python version:  3.9
* Nautobot version:  1.4.8
* nautobot-ssot-ipfabric version:  1.0.0

### Expected Behavior
SSOT errors when Safe Delete Mode is not enabled.

### Observed Behavior
```Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 332, in run
    self.sync_data()
  File "/opt/nautobot/lib/python3.9/site-packages/nautobot_ssot_ipfabric/jobs.py", line 277, in sync_data
    dest.sync_from(ipfabric_source)
  File "/opt/nautobot/lib/python3.9/site-packages/diffsync/__init__.py", line 526, in sync_from
    self.sync_complete(source, diff, flags, syncer.base_logger)
  File "/opt/nautobot/lib/python3.9/site-packages/nautobot_ssot_ipfabric/diffsync/adapter_nautobot.py", line 72, in sync_complete
    nautobot_object.delete()
  File "/opt/nautobot/lib/python3.9/site-packages/django/db/models/base.py", line 960, in delete
    assert self.pk is not None, (
AssertionError: Interface object can't be deleted because its id attribute is set to None.
```

### Steps to Reproduce
1. Start new Sync
2. Uncheck Safe Delete Mode
3.

**Comment by justinjeffery-ipf** [comment]
Happens when Nautobot has data or when Nautobot is completely empty.  It seems it is trying to delete stuff in Nautobot that does not exists.

**Comment by pke11y** [comment]
Thanks @justinjeffery-ipf. I'll take a look.

**Comment by alhogan** [comment]
I've tested this and I believe this has been resolved. If this occurs again please open an issue in the nautobot-ssot repo.
