### ISSUE TITLE
django.core.exceptions when using IP Fabric SSoT after upgrade to Nautobot v1.3.1

### ISSUE THREAD

**Issue by sdargoeuves** [nautobot/nautobot-plugin-ssot-ipfabric#87]
### Environment
* Python version:  3.8.10
* Nautobot version:  1.3.1
* nautobot-ssot-ipfabric version:  0.9.4

### Expected Behavior
Normal completion at the end of the sync

### Observed Behavior

An exception occurred: ValidationError: `{'__all__': ['assigned_object_type and assigned_object_id must either both be null or both be non-null']}`

`Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot/jobs/base.py", line 326, in run
    self.sync_data()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot_ipfabric/jobs.py", line 185, in sync_data
    dest.sync_from(ipfabric_source)
  File "/opt/nautobot/lib/python3.8/site-packages/diffsync/__init__.py", line 525, in sync_from
    result = syncer.perform_sync()
  File "/opt/nautobot/lib/python3.8/site-packages/diffsync/helpers.py", line 326, in perform_sync
    changed |= self.sync_diff_element(element)
  File "/opt/nautobot/lib/python3.8/site-packages/diffsync/helpers.py", line 390, in sync_diff_element
    changed |= self.sync_diff_element(child, parent_model=dst_model)
  File "/opt/nautobot/lib/python3.8/site-packages/diffsync/helpers.py", line 390, in sync_diff_element
    changed |= self.sync_diff_element(child, parent_model=dst_model)
  File "/opt/nautobot/lib/python3.8/site-packages/diffsync/helpers.py", line 366, in sync_diff_element
    changed, modified_model = self.sync_model(src_model=src_model, dst_model=dst_model, ids=ids, attrs=attrs)
  File "/opt/nautobot/lib/python3.8/site-packages/diffsync/helpers.py", line 415, in sync_model
    dst_model = self.model_class.create(diffsync=self.dst_diffsync, ids=ids, attrs=attrs)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot_ipfabric/diffsync/diffsync_models.py", line 306, in create
    ip_address_obj = tonb_nbutils.create_ip(
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot_ipfabric/utilities/nbutils.py", line 143, in create_ip
    tag_object(nautobot_object=ip_obj, custom_field="ssot-synced-from-ipfabric")
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot_ipfabric/utilities/nbutils.py", line 253, in tag_object
    _tag_object(nautobot_object)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot_ipfabric/utilities/nbutils.py", line 251, in _tag_object
    nautobot_object.validated_save()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot/core/models/__init__.py", line 51, in validated_save
    self.full_clean()
  File "/opt/nautobot/lib/python3.8/site-packages/django/db/models/base.py", line 1251, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'__all__': ['assigned_object_type and assigned_object_id must either both be null or both be non-null']}`

### Steps to Reproduce
1. Start the Sync between IP Fabric and Nautobot
2. It works up to the diff and a few steps afterward: 
![image](https://user-images.githubusercontent.com/55829631/164816123-e64ea15e-50d3-40c9-8deb-678cae47b2d5.png)
3. Then it fails

**Comment by chadell** [comment]
addressing in #89

**Comment by glennmatthews** [comment]
Fixed by #89.
